---
title: "flexJAGS"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(rstan)
library(flexjags)

packs = get_packs( pack_dir = pack_dir )

default_pack_content = load_pack( packs[1] )
  

```




Sidebar {.sidebar}
=============

```{r}

tags$style(type="text/css", 
           "textarea { width:100%; height:92%; font-family: monospace;}")

data_html = reactiveValues(data_html_out = "", 
                           desc_html_out = "",
                           post_html_out = "")


selectInput("select_pack", label = "Example pack:",
            choices = packs, selected = packs[1])

actionButton("do_sample", "Sample", icon = icon("play"))

fluidRow(
  column(6, selectInput("n_iter", label = "Iterations",
                        choices = 0, selected = 0)),
  column(6, selectInput("progress_iter", label = "Update",
                        choices = 0, selected = 0))
  )

checkboxInput("eliminate_data", label = "Eliminate data columns?", value = TRUE)


selectInput("plotvar", label = "Variable(s) to plot:",
            choices = "theta", selected = "theta",
            multiple=TRUE, selectize=TRUE)

checkboxInput("render_data", label = "Render output?", value = FALSE)

selectInput("engine", label = "Engine:",
            choices = c("JAGS","stan"), selected = "JAGS")

selectInput("n_chain", label = "Parallel chains:",
                        choices = 1, selected = 1)

update_render = observeEvent(input$render_data, {

  if(!input$render_data){
    shinyjs::disable("post")
  }
})

do_sampling = eventReactive(input$do_sample,{
  
  pack = input$select_pack
  model = input$bugs
  data_txt = input$vars
  init_txt = input$init
  post_txt = input$post
  cur_trace = input$plotvar
  render = input$render_data
  eliminate_data = input$eliminate_data
  
  n_chain = as.integer(input$n_chain)
  n_iter = as.integer(input$n_iter)
  n_progress = as.integer(input$progress_iter)
  
  engine = input$engine

  
  shiny::withProgress(message = "Sampling...", value = 0, {

    incProgress(0, detail = "Evaluating data")
    
    result = eval_data( pack,
                        data_txt = data_txt, 
                        init_txt = init_txt,
                        render = render)
    

    data_html$data_html_out = result$html_out
    
    if(engine == "JAGS"){
      
      samples = flexjags::jags_samples(pack, model, data_html, post_txt, result, n_iter, n_progress, n_chain, cur_trace, eliminate_data, render, session)
      
    }else if(engine == "stan"){
      
      samples = flexjags::stan_samples(pack, model, data_html, post_txt, result, n_iter, n_progress, n_chain, cur_trace, eliminate_data, render, session)
      
    }else{
      
      stop("Unknown engine.")
    
    }
    

  })  

return(samples)
    
})


update_pack = observeEvent(input$select_pack, {
  
  pack = input$select_pack
  pack_content = load_pack( pack )
  data_html$desc_html_out = pack_content$desc_html
  data_html$post_html_out = ""
  data_html$data_html_out = ""
  
  if(input$engine == "JAGS"){
    model_txt = pack_content$jags_txt
    data_txt = pack_content$data_jags_txt
    init_txt = pack_content$init_jags_txt
    post_txt = pack_content$post_jags_txt
  }else if(input$engine == "stan"){
    model_txt = pack_content$stan_txt
    data_txt = pack_content$data_stan_txt
    init_txt = pack_content$init_stan_txt
    post_txt = pack_content$post_stan_txt
  }else{
    stop("Unknown engine.")
  }

  updateTextAreaInput(session, "bugs", value = model_txt)
  updateTextAreaInput(session, "vars", value = data_txt)
  updateTextAreaInput(session, "init", value = init_txt)
  updateTextAreaInput(session, "post", value = post_txt)
  
  updateCheckboxInput(session, "eliminate_data", 
                      value = pack_content$eliminate_data)
  updateCheckboxInput(session, "render_data", 
                      value = pack_content$render_output)  

  updateSelectInput(session, "n_iter",
                    choices = sort(pack_content$iterations),
                    selected = pack_content$iterations[1])
  
  updateSelectInput(session, "progress_iter", 
                    choices = sort(pack_content$update), 
              selected = pack_content$update[1])
  
  updateSelectInput(session, "plotvar", 
                    choices = pack_content$default_var,
              selected = pack_content$default_var)

  updateSelectInput(session, "engine", 
              selected = pack_content$default_engine)
})

update_engine = observeEvent(input$engine, {
  
  pack = input$select_pack
  pack_content = load_pack( pack )
  data_html$post_html_out = ""
  data_html$data_html_out = ""
  
  if(input$engine == "JAGS"){
    model_txt = pack_content$jags_txt
    data_txt = pack_content$data_jags_txt
    init_txt = pack_content$init_jags_txt
    post_txt = pack_content$post_jags_txt
  }else if(input$engine == "stan"){
    model_txt = pack_content$stan_txt
    data_txt = pack_content$data_stan_txt
    init_txt = pack_content$init_stan_txt
    post_txt = pack_content$post_stan_txt
  }else{
    stop("Unknown engine.")
  }

  updateTextAreaInput(session, "bugs", value = model_txt)
  updateTextAreaInput(session, "vars", value = data_txt)
  updateTextAreaInput(session, "init", value = init_txt)
  updateTextAreaInput(session, "post", value = post_txt)
  

})
```



Description
=================

### Example pack description


```{r}

renderUI({
  x = input$select_pack
  div_content = as.character(tags$div(style = "overflow: auto;", HTML(data_html$desc_html_out)))
  return(HTML(div_content))
})

```



Chains {data-orientation=rows}
================


Row
-------------------------------------
    
### MCMC chain
    
```{r}

renderPlot({

  pack = input$select_pack
  input_var = input$plotvar[1]
  
  if(length(input_var)<1){
    return()
  }else if( !(input_var %in% colnames(do_sampling())) ){
    return()
  }
  
  samps = as.vector(do_sampling()[,input_var])
  lo = lowess( samps ~ I(1:length(samps)))
  
  par( flexjags:::par.list )
  
  plot(samps, ty='l', 
       ylab=input_var,
       xlab="Iteration", col = paste0(cols1[5],"99"), lwd=.6)
  
  lines(lo, col=cols1[7],lwd=1)
  
  effN = coda::effectiveSize(samps)
  mtext(substitute(N[eff]==effN, list(effN = round(effN))),
        3, 0, adj = .95, cex = 1, col = "red")

  
})

```
   
Row
-------------------------------------
    
### Marginal density
    
```{r}

renderPlot({
  
  pack = input$select_pack
  input_var = input$plotvar[1]
  
  if(length(input_var)<1){
    return()
  }else if( !(input_var %in% colnames(do_sampling())) ){
    return()
  }
  
  samps = do_sampling()[,input_var]
  
  dens = density(samps)
  qs = quantile(samps, p = c(0.025,0.975))
  
  par( flexjags:::par.list2 )

  plot(dens, ty='n',axes=FALSE,main="",ylab="",xlab=input_var)
  axis(1)
  
  # middle
  idx = (1:length(dens$x))[ dens$x >= qs[1] & dens$x <= qs[2] ]
  polygon(c(dens$x[idx],rev(dens$x[idx])),
        c(dens$y[idx],rep(0,length(idx))),
        border=NA,col = cols1[3])

  # lower 
  idx = which(diff(sign(dens$x - qs[1]))>0)
  polygon(c(dens$x[1:idx],rev(dens$x[1:idx])),
        c(dens$y[1:idx],rep(0,idx)),
        border=NA,col = cols1[6])
  
  # upper 
  idx = which(diff(sign(dens$x - qs[2]))>0)
  polygon(c(dens$x[-(1:idx)],rev(dens$x[-(1:idx)])),
        c(dens$y[-(1:idx)],rep(0,length(dens$x)-idx)),
        border=NA,col = cols1[6])
  
  abline(v = mean(samps),lwd=2, col = cols1[2])

})

```
    
### Autocorrelation function

```{r}

renderPlot({

  pack = input$select_pack
  input_var = input$plotvar[1]
  
  if(length(input_var)<1){
    return()
  }else if( !(input_var %in% colnames(do_sampling())) ){
    return()
  }
  
  samps = do_sampling()[,input_var]
  
  par( flexjags:::par.list )  
  acf(samps, main=input_var)

})

```

Univariate
================

```{r}

renderPlot({

  pack = input$select_pack
  input_vars = input$plotvar
 
  if(length(input_vars) < 2 ) return()
  
  if( !all(input_vars %in% colnames(do_sampling())) ){
    return()
  }
  bayesplot::mcmc_intervals(do_sampling(), input_vars, 
                            prob = .5, prob_outer = .95,
                            point_est = "mean")

})

```



Bivariate
================

```{r}

renderPlot({

  #par( par.list )  
  
  pack = input$select_pack
  input_vars = input$plotvar
 
  if(length(input_vars) < 2 ) return()
  
  if( !all(input_vars %in% colnames(do_sampling())) ){
    return()
  }
  bayesplot::mcmc_pairs(do_sampling(), input_vars,
           off_diag_args = list(size = 1.5), 
           off_diag_fun="hex")

})

```


Summaries
=========

### summary()

```{r}
renderUI({
  
    summary_out = "<b>No samples generated.</b>"
    
    pack = input$select_pack
    samples = do_sampling()
    
    variable_col = apply(samples, 2, function(cl) !all(cl[1] == cl) ) 

  sample_cols = colnames(samples)[ variable_col ]
  
  if( length(sample_cols) > 0 )
    summary_out = paste(capture.output( { summary(samples[, variable_col ]) } ), collapse = "\n")
  
  
  tags$textarea(id = 'summary_out', 
                readonly = "",
  summary_out, columns = 8)
})
```


Model code
=========

### Model

```{r}
tags$textarea(id = 'bugs',  
              autocomplete="off",
              autocorrect="off",
              autocapitalize="off",
              spellcheck="false",
              "", rows = 8)
```


Model inits
=========

The initialization data must be containted in a list or function called `inits`.

```{r}
tags$textarea(id = 'init', "", rows = 8)
```


Data 
=========

Column
--------

### Data expression


```{r}
tags$textarea(id = 'vars',  
              autocomplete="off",
              autocorrect="off",
              autocapitalize="off",
              spellcheck="false",
              "")

```

Column
--------


### Data output 


```{r}

renderUI({
  pack = input$select_pack
  x = do_sampling()
  div_content = as.character(tags$div(style = "overflow: auto;", HTML(data_html$data_html_out)))
  return(HTML(div_content))
})

```


Post-sampling 
=========

Column
--------

The samples will be placed in an `mcmc` object called `samples`.

### Post-sampling expression


```{r}
tags$textarea(id = 'post', 
              autocomplete="off",
              autocorrect="off",
              autocapitalize="off",
              spellcheck="false",
              "")
```

Column
--------


### Post-sampling output 


```{r}

renderUI({
  x = do_sampling()
  pack = input$select_pack
  div_content = as.character(tags$div(style = "overflow: auto;", HTML(data_html$post_html_out)))
  return(HTML(div_content))
})

```
